- name: Install, Build, and Test
  run: |
    npm install
    
    if ($env:OS -eq 'Windows_NT') {
        npm run build --if-present
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Build completed successfully."
        } else {
            Write-Host "Build step not found or failed, continuing..."
        }

        npm run test --if-present
        if ($LASTEXITCODE -eq 0) {
            Write-Host "Tests completed successfully."
        } else {
            Write-Host "No tests specified or tests failed, continuing..."
        }
    } else {
        set -e
        if npm run build --if-present; then
            echo "Build completed successfully."
        else
            echo "Build step not found or failed, continuing..."
        fi

        if npm run test --if-present; then
            echo "Tests completed successfully."
        else
            echo "No tests specified or tests failed, continuing..."
        fi
    }
